import os

OPENAI_DEPLOYMENT_NAME= os.getenv('AZURE_OPENAI_DEPLOYMENT')
OPENAI_EMBEDDING_MODEL_NAME=os.getenv('OPENAI_EMBEDDINGS_MODEL_NAME')
OPENAI_ENDPOINT=os.getenv("OPENAI_ENDPOINT")
OPENAI_API_KEY=os.getenv("OPENAI_API_KEY")

# DIR_PATH = 'resources'
